apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - max: # max and min define the limit range
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 100Mi
    type: Container

  - max: # max and min define the limit range
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 100Mi
    type: Pod
