apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sc1
  name: sc1
spec:
  containers:
  - image: httpd
    name: sc1
    securityContext: 
      privileged: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
