apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sc2
  name: sc2
spec:
  containers:
  - image: gcr.io/google-samples/node-hello:1.0
    name: sc2
    securityContext: 
      capabilities: 
        drop: ["CHOWN"]
