apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sc3
  name: sc3
spec:
  securityContext: 
    runAsUser: 1000
  containers:
  - image: gcr.io/google-samples/node-hello:1.0
    name: sc2
    securityContext: 
      runAsUser: 1000
      allowPrivilegeEscalation: false
