apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysvc1
  name: mysvc1
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mysvc1
  type: ClusterIP
status:
  loadBalancer: {}
