apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test1
  name: test1
spec:
  ports:
  - name: "8080"
    port: 8080
    nodePort: 31000
    protocol: TCP
    targetPort: 8080
  selector:
    app: test1
  type: NodePort
status:
  loadBalancer: {}
