apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mydb1
  name: cmmydb
spec:
  containers:
  - envFrom:
    - configMapRef:
       name: mayank 
    image: mysql
    name: mydb1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
