apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mayank
  name: mayank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mayank
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mayank
    spec:
      nodeName: worker01
      volumes: 
      - name: mayank 
        persistentVolumeClaim: 
         claimName: myclaim
      containers:
      - image: httpd
        name: httpd
        volumeMounts: 
        - name: mayank
          mountPath: /usr/local/apache2/htdocs/
